# Generated by Django 2.1.3 on 2018-11-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('backend_id', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('bookings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TourMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='media')),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour')),
            ],
        ),
    ]
