# Generated by Django 2.1.3 on 2018-11-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmedia',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tour',
            name='url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tourmedia',
            name='category',
            field=models.CharField(default='', max_length=300),
        ),
    ]
