# Generated by Django 2.1.3 on 2018-11-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20181120_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=300)),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('booking_reference', models.CharField(default='', max_length=300)),
                ('event_day', models.DateField()),
                ('people', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[['c', 'confirmed'], ['p', 'pending'], ['o', 'open']], max_length=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='TourReview',
            new_name='Review',
        ),
        migrations.RemoveField(
            model_name='tourmedia',
            name='tour_id',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='backend_id',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='bookings',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.DeleteModel(
            name='TourMedia',
        ),
        migrations.AddField(
            model_name='order',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Order'),
        ),
    ]
