# Generated by Django 2.1.3 on 2018-11-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20181120_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tour',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
