# Generated by Django 2.1.3 on 2018-11-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_auto_20181120_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='url',
            field=models.SlugField(default='', max_length=300, unique=True),
        ),
    ]
