# Generated by Django 2.1.3 on 2018-11-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_auto_20181120_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='tour',
            name='url',
            field=models.SlugField(default='', max_length=250, unique=True),
        ),
    ]
