# Generated by Django 2.1.3 on 2018-11-20 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0006_auto_20181120_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('booking_reference', models.CharField(default='', max_length=300)),
                ('event_day', models.DateField()),
                ('people', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[['c', 'confirmed'], ['p', 'pending'], ['o', 'open']], max_length=1)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour')),
            ],
        ),
    ]
